import { Sweet, CustomBoxSize, Testimonial } from './types';

export const HERO_IMAGE = '/src/assets/images/aangan_hero_1780859163579.png';
export const MITHAI_BOX_IMAGE = '/src/assets/images/mithai_box_1780859174779.png';

export const MENU_ITEMS: Sweet[] = [
  // --- SWEETS (mithai) ---
  {
    id: '1',
    name: 'Alsi Pinni',
    description: 'Nutritious and rich winter-special flatseed pinni, slow-toasted in pure ghee with whole wheat flour and loaded with chopped nuts.',
    category: 'mithai',
    price: 10.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1505576391880-b3f9d713dc4f?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Winter Special', 'Pure Ghee'],
    color: '#78350F',
    emoji: '🟤',
    ingredients: ['Flax Seeds (Alsi)', 'Whole Wheat Flour', 'Pure Ghee', 'Almonds', 'Jaggery']
  },
  {
    id: '2',
    name: 'Atta Pinni',
    description: 'Traditional Punjabi sweet roundels made of slow-roasted whole wheat flour in rich cow ghee with a delicate touch of cardamoms.',
    category: 'mithai',
    price: 12.99,
    weightText: 'per lb',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Pure Ghee', 'Rich Khoya'],
    color: '#B45309',
    emoji: '🟡',
    ingredients: ['Whole Wheat Flour', 'Pure Ghee', 'Cardamom', 'Melon Seeds', 'Sugar']
  },
  {
    id: '3',
    name: 'Badana',
    description: 'Crispy sweet tiny gram-flour pearls fried golden in ghee and soaked beautifully in spiced cardamom syrup. (Currently Out of Stock)',
    category: 'mithai',
    price: 8.99,
    weightText: 'per lb',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Out Of Stock', 'Crispy Sweet', 'Festive Special'],
    color: '#F97316',
    emoji: '🟠',
    ingredients: ['Gram Flour (Besan)', 'Sugar Syrup', 'Cardamom', 'Pure Ghee']
  },
  {
    id: '4',
    name: 'Besan Burfi',
    description: 'Melt-in-mouth roasted chickpea flour diamond fudge cooked slowly with sugar and rich ghee, garnished with almond flakes.',
    category: 'mithai',
    price: 9.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1605197585662-dc09204bc99e?auto=format&fit=crop&q=80&w=800',
    tags: ['Pure Ghee', 'Best Seller', 'Gluten-Free'],
    color: '#FBBF24',
    emoji: '🔶',
    ingredients: ['Gram Flour (Besan)', 'Ghee', 'Sugar', 'Cardamom', 'Almonds']
  },
  {
    id: '5',
    name: 'Besan Ladoo',
    description: 'Fragrant and classic hand-rolled chickpea flour sweet spheres roasted in premium ghee and seasoned with cardamoms.',
    category: 'mithai',
    price: 12.99,
    weightText: 'per lb',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Pure Ghee', 'Best Seller'],
    color: '#FBBF24',
    emoji: '🟡',
    ingredients: ['Coarse Besan', 'Pure Ghee', 'Cardamom', 'Melon Seeds']
  },
  {
    id: '6',
    name: 'Boondi Ladoo',
    description: 'Juicy and delicious golden sweet balls made from fine fried gram-flour pearls pressed with pure ghee and melon seeds.',
    category: 'mithai',
    price: 8.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Kid-Friendly', 'Festive Favorite'],
    color: '#F59E0B',
    emoji: '🟠',
    ingredients: ['Chickpea Flour', 'Sugar Syrup', 'Melon Seeds', 'Spices']
  },
  {
    id: '7',
    name: 'Chum Chum',
    description: 'Succulent, oblong cottage cheese sweet patties soaked in piping hot light sugar water syrup and coated in dry desiccated coconut.',
    category: 'mithai',
    price: 11.99,
    weightText: 'per lb',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800',
    tags: ['Bengali Classic', 'Spongy', 'Saffron-Infused'],
    color: '#F3F4F6',
    emoji: '🍢',
    ingredients: ['Chenna (Milk Curd)', 'Sugar', 'Desiccated Coconut', 'Kewra Essence']
  },
  {
    id: '8',
    name: 'Dodha Burfi',
    description: 'Intensely rich, chewy, and grainy caramelized milk fudge cooked beautifully with cracked wheat, ghee, and loaded with roasted nuts.',
    category: 'mithai',
    price: 10.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1605197585662-dc09204bc99e?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Rich Khoya', 'Traditional'],
    color: '#78350F',
    emoji: '🟫',
    ingredients: ['Milk Solids', 'Sprouted Wheat', 'Sugar', 'Pure Ghee', 'Almonds', 'Cashews']
  },
  {
    id: '9',
    name: 'Flax Seed Ladoo',
    description: 'Nourishing and delicious flax seed sweet globes rolled by hand with pure raw jaggery, roasted grains, and ghee. A healthy choice.',
    category: 'mithai',
    price: 10.99,
    weightText: 'per lb',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1505576391880-b3f9d713dc4f?auto=format&fit=crop&q=80&w=800',
    tags: ['Vegan-Friendly', 'Healthy Touch', 'Winter Ritual'],
    color: '#3F2305',
    emoji: '🟤',
    ingredients: ['Flax Seeds', 'Whole Wheat', 'Pure Jaggery', 'Ghee', 'Nuts']
  },
  {
    id: '10',
    name: 'Gajar Burfi',
    description: 'A luscious orange-red fudge prepared with grated sweet carrots, rich condensed milk solids (khoya), sugar, and green cardamoms.',
    category: 'mithai',
    price: 10.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Rich Khoya', 'Winter Classic'],
    color: '#EF4444',
    emoji: '🥕',
    ingredients: ['Grated Sweet Carrots', 'Milk Solids (Mawa)', 'Sugar', 'Ghee', 'Pistachios']
  },
  {
    id: '11',
    name: 'Gulab Jaman',
    description: 'Delightfully soft, golden-brown fried milk solids balls, thoroughly drenched in rose syrup and cardamom sugar nectar.',
    category: 'mithai',
    price: 9.99,
    weightText: 'per lb',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Classic Treat', 'Aromatic Spice'],
    color: '#78350F',
    emoji: '🟤',
    ingredients: ['Condensed Milk Powder', 'Wheat Flour', 'Ghee', 'Cardamom Syrup', 'Rosewater']
  },
  {
    id: '12',
    name: 'Jalebi',
    description: 'Crisp spiral wild-yeast funnel loops fried to golden amber in pure ghee and submerged hot in cardamom-infused sugar syrup.',
    category: 'mithai',
    price: 8.99,
    weightText: 'per lb',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Fried Fresh', 'Crispy', 'Best Seller'],
    color: '#F59E0B',
    emoji: '🌀',
    ingredients: ['Fermented Batter', 'Sugar Syrup', 'Saffron', 'Pure Ghee']
  },
  {
    id: '13',
    name: 'Kaju Katti',
    description: 'Elegant trademark diamond melts made from finely grounded premium quality dry cashew nut meal and light sweet syrup. Classic gift.',
    category: 'mithai',
    price: 14.99,
    weightText: 'per lb',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1605197585662-dc09204bc99e?auto=format&fit=crop&q=80&w=800',
    tags: ['Gift Classic', 'Pure Cashew', 'Vegan-Friendly'],
    color: '#E5E7EB',
    emoji: '💎',
    ingredients: ['Premium Cashews', 'Sugar', 'Pure Ghee', 'Edible Silver Leaf']
  },
  {
    id: '14',
    name: 'Kalakand',
    description: 'Soft, creamy, granular milk cake bars made with fresh curd cheese and double whole milk, sweet spiced with cardamoms.',
    category: 'mithai',
    price: 11.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1505576391880-b3f9d713dc4f?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Granular Delight', 'Rich Khoya'],
    color: '#F9FAFB',
    emoji: '⬜',
    ingredients: ['Fresh Paneer Curd', 'Thickened Milk', 'Rosewater', 'Pistachio Shavings']
  },
  {
    id: '15',
    name: 'Khoya kesar peda',
    description: 'A traditional semi-soft sweet milk-solids fudge prepared slowly with saffron lines, organic sugar, and premium cardamom.',
    category: 'mithai',
    price: 13.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Saffron-Infused', 'Aromatic Spice', 'Rich Khoya'],
    color: '#FDE047',
    emoji: '🔸',
    ingredients: ['Unsweetened Khoya', 'Kashmiri Saffron', 'Sugar', 'Pistachios']
  },
  {
    id: '16',
    name: 'Milk Cake',
    description: 'The golden crown of milk fudge: granular brown and white dual-tone caramelized curd solids blocks seasoned with ghee.',
    category: 'mithai',
    price: 11.49,
    weightText: 'per lb',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1505576391880-b3f9d713dc4f?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Traditional', 'Grand Classic'],
    color: '#F3E8FF',
    emoji: '🥛',
    ingredients: ['Whole Milk', 'Sugar', 'Pure Ghee', 'Alum Touch']
  },
  {
    id: '17',
    name: 'Pista Burfi',
    description: 'Smooth pistachio-infused mawa milk fudge with real crumbled premium nutty bits and delicate whole cream.',
    category: 'mithai',
    price: 10.99,
    weightText: 'per lb',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1605197585662-dc09204bc99e?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Gluten-Free', 'Aromatic Spice'],
    color: '#10B981',
    emoji: '🟢',
    ingredients: ['Toasted Pistachios', 'Mawa Milk Paste', 'Cardamom', 'Almonds']
  },
  {
    id: '18',
    name: 'Punjabi Burfi',
    description: 'A rich and heavy Punjabi-accented dense cream solid fudge, mildly sweetened and highly rich in pure ghee texture.',
    category: 'mithai',
    price: 12.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1605197585662-dc09204bc99e?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Pure Ghee', 'Traditional'],
    color: '#E5E7EB',
    emoji: '⬜',
    ingredients: ['Cream Milk Solids', 'Organic Sugar', 'Pistachio flakes', 'Ghee']
  },
  {
    id: '19',
    name: 'Ras Malai',
    description: 'Delicate, soft and spongy cottage-cheese patties soaked in cardamon-and-saffron-infused sweet milk rubri. Price covers servings ranging from $4.49 - $12.99.',
    category: 'mithai',
    price: 4.49,
    weightText: 'per plate',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Saffron-Infused', 'Gluten-Free'],
    color: '#FBBF24',
    emoji: '🥛',
    ingredients: ['Cottage Cheese', 'Sweet Saffron Milk Rabri', 'Pistachios', 'Almonds']
  },
  {
    id: '20',
    name: 'Rasgulla',
    description: 'Succulent, circular spongy milk cheese dumplings boiled in light cardamom scented clear pure sugar water syrup.',
    category: 'mithai',
    price: 11.99,
    weightText: 'per lb',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800',
    tags: ['Bengali Classic', 'Spongy', 'Gluten-Free'],
    color: '#F3F4F6',
    emoji: '⚪',
    ingredients: ['Fresh Cottage Cheese', 'Sugar Syrup', 'Kewra Essence']
  },
  {
    id: '21',
    name: 'Stuffed Gulab Jamun',
    description: 'Luxe golden-brown dumpling spheres stuffed with finely chopped roasted almonds, cashews, and saffron threads inside.',
    category: 'mithai',
    price: 11.99,
    weightText: 'per lb',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Aromatic Spice', 'Best Seller', 'Rich Khoya'],
    color: '#78350F',
    emoji: '🟤',
    ingredients: ['Milk Solids', 'Pistachios', 'Almond Stuffing', 'Saffron Sugar water']
  },
  {
    id: '22',
    name: 'Till Ladoo',
    description: 'Crispy winter delicacy balls hand-rolled of premium sesame seeds caramelized together with sweet organic jaggery syrup.',
    category: 'mithai',
    price: 12.99,
    weightText: 'per lb',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Vegan-Friendly', 'Healthy Touch'],
    color: '#D97706',
    emoji: '🟡',
    ingredients: ['Sesame Seeds (Til)', 'Pure Jaggery (Gur)', 'Pure Ghee', 'Cardamom']
  },

  // --- APPETIZERS (chaat) ---
  {
    id: '23',
    name: 'Aloo Chaat',
    description: 'Golden-crispfried potato wedges tossed gently in sweet tamarind chutneys, spicy mint dips, roasted cumin, and black salt.',
    category: 'chaat',
    price: 7.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Savory Snack', 'Vibrant', 'Gluten-Free'],
    color: '#D97706',
    emoji: '🍟',
    ingredients: ['Fried Potato Wedges', 'Chaat Masala', 'Tamarind Glaze', 'Mint Powder']
  },
  {
    id: '24',
    name: 'Bhalla Papri',
    description: 'Cool combination of soaked spiced lentil dumplings and crisp flat pastry chips layered with custom spiced curd.',
    category: 'chaat',
    price: 7.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Savory Snack', 'Local Favorite'],
    color: '#10B981',
    emoji: '🥗',
    ingredients: ['Lentil Dumplings', 'Papri Chips', 'Whipped Yogurt', 'Sweet Chutney']
  },
  {
    id: '25',
    name: 'Bhel Puri',
    description: 'Vibrant puffed rice salad tossed beautifully with fine onion cubes, crunchy sev, green chili, and tangy tamarind lime juice.',
    category: 'chaat',
    price: 6.49,
    weightText: 'per portion',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Vegan-Friendly', 'Crispy', 'Light Snack'],
    color: '#84CC16',
    emoji: '🥣',
    ingredients: ['Puffed Rice', 'Chickpea Sev', 'Raw Onions', 'Tamarind Pulp']
  },
  {
    id: '26',
    name: 'Chana Chat',
    description: 'Tender boiled chickpeas salad combined with raw red onions, diced ripe tomato, lemon juices, and roasted spices.',
    category: 'chaat',
    price: 8.49,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Gluten-Free', 'Vegan-Friendly', 'Healthy Touch'],
    color: '#059669',
    emoji: '🥗',
    ingredients: ['Kabuli Chickpeas', 'Onions', 'Tomatoes', 'Chaat Masala', 'Lemon']
  },
  {
    id: '27',
    name: 'Dahi Puri',
    description: 'Vibrant hollow semolina pastry shells stuffed with potato-chickpea salad, topped with sweet yogurt and fine sev. (Currently Out of Stock)',
    category: 'chaat',
    price: 8.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Out Of Stock', 'Cold & Tangy', 'Best Seller'],
    color: '#3B82F6',
    emoji: '⚪',
    ingredients: ['Crisp Puris', 'Mashed Potato', 'Sweetened Curd', 'Sev Crunch', 'Herbs']
  },
  {
    id: '28',
    name: 'Dahi Vada',
    description: 'Chilled soft lentil fritter balls soaked in seasoned premium whipped cream yogurt, sweet tamarind, and fine roasted cumin.',
    category: 'chaat',
    price: 7.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Cold & Tangy', 'Gluten-Free', 'Traditional'],
    color: '#10B981',
    emoji: '🥣',
    ingredients: ['Urad Dal Fritters', 'Silky Yogurt', 'Tamarind Pods', 'Spiced Herbs']
  },
  {
    id: '29',
    name: 'Pakora',
    description: 'Fresh fritters bundled with chickpea batter fried crisp. Deliciously hot savory appetizer. Price reflects selection options from $3.99 - $5.99.',
    category: 'chaat',
    price: 3.99,
    weightText: 'per portion',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Fried Fresh', 'Vegan-Friendly', 'Crispy'],
    color: '#D97706',
    emoji: '🍤',
    ingredients: ['Onions & Spinach', 'Granulated Gram Flour', 'Green Chilies', 'Dips']
  },
  {
    id: '30',
    name: 'Pani Poori',
    description: 'Eight wafer-thin semolina bubbles served with herbed mint water, tamarind chutney, and a customized savory potato-chana stuffing.',
    category: 'chaat',
    price: 5.99,
    weightText: '8 Pieces',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Street Special', 'Best Seller', 'DIY Platter'],
    color: '#84CC16',
    emoji: '🟢',
    ingredients: ['Semolina Shells', 'Mint Herb water', 'Sweet Tamarind water', 'Boiled potato']
  },
  {
    id: '31',
    name: 'Papri Chat',
    description: 'Shattered wheat chips layered with sweet curd, cooked black garbanzos, spicy house mint sauce, and tamarind glaze.',
    category: 'chaat',
    price: 7.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Street Special', 'Classic Treat', 'Local Favorite'],
    color: '#F43F5E',
    emoji: '🥗',
    ingredients: ['Wheat Flour Papri', 'Boiled Potatoes', 'Whipped Yogurt', 'Tangy Mint sauce']
  },
  {
    id: '32',
    name: 'Samosa Chat',
    description: 'Golden spiced potato samosa pyramid smashed and drowned in warm masala chickpeas, cold curds, sweet-spicy chutneys. Price ranges $7.99 - $10.99.',
    category: 'chaat',
    price: 7.99,
    weightText: 'per plate',
    rating: 4.9,
    image: '/src/assets/images/samosa_chaat_1780859197593.png',
    tags: ['Best Seller', 'Hot & Savory', 'Local Favorite'],
    color: '#EF4444',
    emoji: '🥗',
    ingredients: ['Potato Samosa', 'Chana Masala', 'Curd Yogurt', 'Mint Tamarind chutney']
  },
  {
    id: '33',
    name: 'Sev Puri',
    description: 'Crispy papri crackers stuffed with potatoes, onions, a duo of house herb chutneys, and premium fine crispy sev.',
    category: 'chaat',
    price: 6.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Local Favorite', 'Crispy', 'Street Special'],
    color: '#EAB308',
    emoji: '🥗',
    ingredients: ['Crisp puri chips', 'Aloo Mash', 'Sweet Mango chutney', 'Yellow Sev']
  },
  {
    id: '34',
    name: 'Veg. Samosa',
    description: 'Crispy triangle wheat wraps packed with heavily seasoned potatoes, peas, and house masala. Serving option ranges $4.49 - $4.99.',
    category: 'chaat',
    price: 4.49,
    weightText: 'per serving',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Vegan-Friendly', 'Best Seller', 'Crispy'],
    color: '#D97706',
    emoji: '🔺',
    ingredients: ['Wheat Pastry', 'Aromatic Potatoes', 'Peas', 'Spices']
  },
  {
    id: '35',
    name: 'Kachori',
    description: 'Golden, round flaky pastry balls stuffed with high spiced yellow moong dal paste, served with tamarind chutney. Serving options $3.99 - $6.99.',
    category: 'chaat',
    price: 3.99,
    weightText: 'per serving',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Crispy', 'Traditional', 'Savory Snack'],
    color: '#B45309',
    emoji: '🍪',
    ingredients: ['Refined Flour Dough', 'Lentil Paste', 'Mustard seeds', 'Masala']
  },

  // --- SPECIALS / COMBOS (combos) ---
  {
    id: '36',
    name: 'Chole Bhature',
    description: 'A traditional hearty North Indian feast. Two hot puffed fried bhaturas (leavened bread) served with rich, spiced chickpea curry, raw onions, and tangy pickles.',
    category: 'combos',
    price: 11.99,
    weightText: 'per plate',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Hearty Meal', 'Fresh Fried'],
    color: '#854D0E',
    emoji: '🥯',
    ingredients: ['Leavened Maida Bread', 'Dark Chickpea Chana Curry', 'Lemon', 'In-House Hot Pickle']
  },
  {
    id: '37',
    name: 'Aloo Bhatura',
    description: 'Two piping hot bhatura breads stuffed with lightly spiced mashed potatoes, paired beautifully with customized choley curry.',
    category: 'combos',
    price: 11.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Hearty Meal', 'Best Seller'],
    color: '#818CF8',
    emoji: '🍞',
    ingredients: ['Potato-stuffed bread', 'Spicy dark chickpeas', 'Citrus onion salad']
  },
  {
    id: '38',
    name: 'Poori Choley',
    description: 'Three freshly puffed golden-crispier whole wheat puris paired symmetrically with a robust spicy dark chickpea curry bowl.',
    category: 'combos',
    price: 11.99,
    weightText: 'per plate',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Rich Khoya', 'Traditional'],
    color: '#B45309',
    emoji: '🟢',
    ingredients: ['Whole Wheat Flour rotis', 'Kabuli chickpeas', 'Indian masala', 'Pickled mango']
  },
  {
    id: '39',
    name: 'Poori Bhaji',
    description: 'Three crispy wheat puris served together with dry tempered Punjabi-style potato aloo bhaji curry cooked in mustard seeds.',
    category: 'combos',
    price: 11.99,
    weightText: 'per plate',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Hearty Meal', 'Best Seller', 'Traditional'],
    color: '#D97706',
    emoji: '🍛',
    ingredients: ['Atta wheat puris', 'Aloo Dry Bhaji', 'Turmeric', 'Green Chilies']
  },
  {
    id: '40',
    name: 'Extra Bhatura',
    description: 'A single piece of hot, freshly puffed bhatura leavened fried flatbread.',
    category: 'combos',
    price: 3.99,
    weightText: '1 piece',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Side Order', 'Fresh Fried'],
    color: '#E5E7EB',
    emoji: '🥠',
    ingredients: ['White Refined Flour', 'Leavening yeast']
  },
  {
    id: '41',
    name: 'Extra Poori',
    description: 'A single piece of freshly puffed golden-crispiest whole wheat fried poori.',
    category: 'combos',
    price: 3.99,
    weightText: '1 piece',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    tags: ['Side Order', 'Fresh Fried'],
    color: '#F97316',
    emoji: '🪙',
    ingredients: ['Whole Wheat Atta', 'Vegetable Oil']
  },
  {
    id: '42',
    name: 'Paneer Prantha',
    description: 'Tawa-grilled whole wheat paratha flatbread stuffed with spiced hand-scrambled paneer cheese, served with fresh butter.',
    category: 'combos',
    price: 9.99,
    weightText: 'per plate',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Freshly Baked', 'Aromatic Spice'],
    color: '#B45309',
    emoji: '🥞',
    ingredients: ['Whole Wheat Dough', 'Paneer Mash', 'Spiced Herbs', 'Butter']
  },
  {
    id: '43',
    name: 'Tawa Roti',
    description: 'Thin, completely soft home-style flatbread cooked on griddle tawa with a light brush of butter or ghee.',
    category: 'combos',
    price: 1.99,
    weightText: '1 piece',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=800',
    tags: ['Side Order', 'Vegan-Friendly', 'Healthy Touch'],
    color: '#D97706',
    emoji: '🫓',
    ingredients: ['Whole wheat flour', 'Ghee']
  },

  // --- TRADITIONAL DISHES (dishes) ---
  {
    id: '44',
    name: 'Rajma Masala',
    description: 'Savory red kidney beans simmered slowly until fully tender in rich thick aromatic ginger-onion-tomato thick gravy. Portions range from $12.99 - $24.99.',
    category: 'dishes',
    price: 12.99,
    weightText: 'per portion',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Gluten-Free', 'Healthy Touch', 'Traditional'],
    color: '#78350F',
    emoji: '🍛',
    ingredients: ['Red Kidney Beans', 'Onions', 'Tomato Paste', 'Ginger', 'House Masala']
  },
  {
    id: '45',
    name: 'Aloo Gobi',
    description: 'Fresh diced garden potatoes and cauliflower florets sautéed beautifully dry with organic ginger, turmeric, and cumin seed. Portions range from $14.99 - $28.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Gluten-Free', 'Vegan-Friendly', 'Traditional'],
    color: '#EAB308',
    emoji: '🥔',
    ingredients: ['Potatoes', 'Fresh Cauliflower', 'Ginger Juliennes', 'Turmeric Cumin']
  },
  {
    id: '46',
    name: 'Shahi Paneer',
    description: 'Soft cottage cheese paneer cubes folded into a luxurious rich, creamy sweet onion-cashew thick gravy dotted with saffron. Portions range from $15.99 - $28.99.',
    category: 'dishes',
    price: 15.99,
    weightText: 'per portion',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Rich Khoya', 'Specialty'],
    color: '#FBBF24',
    emoji: '🧀',
    ingredients: ['Fresh Paneer Chunks', 'Premium Cashews', 'Fresh Milk Cream', 'Cardamom', 'Saffron']
  },
  {
    id: '47',
    name: 'Baingan Bhartha',
    description: 'Charcoal smoky tandoor-roasted eggplant mash cooked dry with sweet green peas, chopped red onions, garlic, and fresh herbs. Portions range from $14.99 - $29.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Vegan-Friendly', 'Gluten-Free', 'Traditional'],
    color: '#7C3AED',
    emoji: '🍆',
    ingredients: ['Smoky Fire Ground Eggplants', 'Tomato Mash', 'Garlic Paste', 'Green Peas']
  },
  {
    id: '48',
    name: 'Sarso Saag',
    description: 'Highly authentic Punjabi winter favorite of slow-simmered mustard green leaves tempered with home cow ghee, spicy ginger, and white corn powder. Portions range from $9.99 - $28.99.',
    category: 'dishes',
    price: 9.99,
    weightText: 'per portion',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Pure Ghee', 'Traditional'],
    color: '#065F46',
    emoji: '🥬',
    ingredients: ['Mustard Greens', 'Spinach Leaves', 'Indian Ghee', 'Fresh Garlic', 'Ginger']
  },
  {
    id: '49',
    name: 'Matar Paneer',
    description: 'Earthy classic cottage cheese cubes combined together with sweet tender green peas in red spiced onion-tomato masala. Portions range from $14.99 - $28.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Gluten-Free', 'Classic Treat'],
    color: '#E11D48',
    emoji: '🍲',
    ingredients: ['Cheese Paneer Chunks', 'Green Peas', 'Onion-tomato gravy', 'Coriander dust']
  },
  {
    id: '50',
    name: 'Kadai Paneer',
    description: 'Diced soft paneer cheese tossed with whole sliced green bell peppers, chunky onion squares, fresh tomato, and spicy hand-pounded kadai masalas. Portions range from $14.99 - $28.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Aromatic Spice', 'Traditional'],
    color: '#B45309',
    emoji: '🥘',
    ingredients: ['Paneer cubes', 'Mixed Bell Peppers', 'Spicy Kadai Seeds', 'Onion slice']
  },
  {
    id: '51',
    name: 'Paneer Makhani',
    description: 'Juicy cubes of paneer cheese simmered slowly inside a velvety tomato butter and cream paste with dry fenugreek leaves. Portions range from $14.99 - $28.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Creamy Yogurt', 'Specialty'],
    color: '#EA580C',
    emoji: '🍛',
    ingredients: ['Paneer Curds', 'Makhani butter glaze', 'Sweet Cream', 'Kasuri Methi']
  },
  {
    id: '52',
    name: 'Saag Choley',
    description: 'Savory organic dark chickpeas slow-cooked to tenderness inside a pureed, well-spiced earth tempered spinach leaf saag sauce. Portions range from $14.99 - $29.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Traditional', 'Gluten-Free', 'Healthy Touch'],
    color: '#15803D',
    emoji: '🥬',
    ingredients: ['Sautéed Spinach', 'Organic Chickpeas', 'Whole Ginger Masala', 'Herbs']
  },
  {
    id: '53',
    name: 'Saag Paneer',
    description: 'Cottage cheese cubes folded lovingly into fresh thick creamed pureed green spinach saag with ginger garlic. Portions range from $14.99 - $28.99.',
    category: 'dishes',
    price: 14.99,
    weightText: 'per portion',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Gluten-Free', 'Traditional'],
    color: '#166534',
    emoji: '🥘',
    ingredients: ['Paneer Cheeses', 'Tendered Spinach mash', 'Ginger Garlick', 'Dairy cream']
  },
  {
    id: '54',
    name: 'Daal Makhani',
    description: 'The golden jewel of dals: slow-cooked black urad beans and kidney beans simmered overnight with tomatoes, hand-churned butter, and cream. Portions range from $12.99 - $24.99.',
    category: 'dishes',
    price: 12.99,
    weightText: 'per portion',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Pure Ghee', 'Winter Classic'],
    color: '#451A03',
    emoji: '🍲',
    ingredients: ['Black Urad Beans', 'Kidney Beans', 'Pure Butter', 'Fresh Cream', 'Ginger Garlick']
  },
  {
    id: '55',
    name: 'Aloo Saag',
    description: 'Golden simmer potato slices cooked down in spiced spinach and mustard leafy greens tempering with cumin. Portions range from $13.99 - $27.99.',
    category: 'dishes',
    price: 13.99,
    weightText: 'per portion',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    tags: ['Gluten-Free', 'Vegan-Friendly', 'Healthy Touch'],
    color: '#14532D',
    emoji: '🥬',
    ingredients: ['Wedge Potatoes', 'Tempered Spinach puree', 'Turmeric', 'Cumin Masala']
  },

  // --- BEVERAGES (drinks) ---
  {
    id: '56',
    name: 'Chai',
    description: 'Piping hot loose-leaf tea simmered slowly with ginger, cardamom pods, black milk and light sugar, served warm.',
    category: 'drinks',
    price: 3.99,
    weightText: 'per cup',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800',
    tags: ['Aromatic Spice', 'Hot Drink', 'Best Seller'],
    color: '#78350F',
    emoji: '☕',
    ingredients: ['Assam Black Tea', 'Cardamom', 'Ginger', 'Chilled Milk']
  },
  {
    id: '57',
    name: 'Coffee',
    description: 'Homestyle frothy hot Indian filter coffee brewed delightfully with whole milk and high roasted coffee bean dust.',
    category: 'drinks',
    price: 2.99,
    weightText: 'per cup',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800',
    tags: ['Hot Drink', 'Spiced Touch', 'Light Item'],
    color: '#3F2305',
    emoji: '☕',
    ingredients: ['Dark Ground Coffee', 'Boiled Whole Milk', 'Sugar cream']
  },
  {
    id: '58',
    name: 'Lassi',
    description: 'Chilled sweet churned yogurt smoothie. Very refreshing beverage option. Price ranges from $3.99 - $4.49 depending on customization.',
    category: 'drinks',
    price: 3.99,
    weightText: 'per glass',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800',
    tags: ['Chilled', 'Cold & Tangy', 'Traditional'],
    color: '#F9FAFB',
    emoji: '🥛',
    ingredients: ['Yogurt solids', 'Ice cubes', 'Cardamom or salt dust', 'Rosewater essence']
  },
  {
    id: '59',
    name: 'Mango Milkshake',
    description: 'Sultry, rich milkshake prepared with sweet Alphonso Mango pulp whipped together with organic whole milk and ice.',
    category: 'drinks',
    price: 4.49,
    weightText: 'per glass',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800',
    tags: ['Best Seller', 'Chilled', 'Sweet Delight'],
    color: '#F59E0B',
    emoji: '🥭',
    ingredients: ['Sweet Mango Pulps', 'Full fat milk', 'Vanilla touch', 'Sugar']
  },
  {
    id: '60',
    name: 'Cold Drink',
    description: 'Chilled assorted canned pops or heavy glass bottle soda options of your flavor choice ($1.25 to $3.99).',
    category: 'drinks',
    price: 1.25,
    weightText: 'can/bottle',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800',
    tags: ['Chilled', 'Sparkling', 'Light Item'],
    color: '#3B82F6',
    emoji: '🥤',
    ingredients: ['Assorted Soft Drinks', 'Carbonated Water']
  }
];

export const CUSTOM_BOX_SIZES: CustomBoxSize[] = [
  {
    id: 'small',
    name: 'Shahi Uphar Box',
    slots: 4,
    dimensionsText: '2x2 Traditional Grid',
    price: 15.99,
    weightText: 'approx. 250g',
    description: 'A perfect sweet gesture for an intimate tea pairing or a thoughtful token of appreciation.'
  },
  {
    id: 'medium',
    name: 'Aangan Court Box',
    slots: 9,
    dimensionsText: '3x3 Artisan Grid',
    price: 29.99,
    weightText: 'approx. 500g',
    description: 'Our most popular choice. Beautifully curated to showcase an authentic spectrum of texture and saffron flavor.'
  },
  {
    id: 'large',
    name: 'Maharani Feast Box',
    slots: 16,
    dimensionsText: '4x4 Royal Grid',
    price: 49.99,
    weightText: 'approx. 1000g (1kg)',
    description: 'A luxurious custom platter designed for large family gatherings, majestic corporate gifting, and grand festivals.'
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Harshil Shah',
    location: 'Hamilton Local (Verified Google Review)',
    text: 'Their fresh hot Jalebi is outstanding—always served warm, crispy, and perfectly sweet. We also customized a sweet gift box with Kaju Katli and Motichoor Ladoo for a family gathering, and the presentation was absolutely beautiful.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: '2',
    name: 'Melissa K.',
    location: 'West Chester Resident (Verified Yelp Review)',
    text: 'I drive out here just for their Samosa Chaat and Gujarati Dhokla. The Samosa Chaat is perfectly balanced between spicy, sweet, and tangy, and the Dhokla is so soft, fresh, and light!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: '3',
    name: 'Amit Patel',
    location: 'Local Google Local Guide',
    text: 'Finally, an authentic sweet shop in the Butler County area! The Rasmalai is pillowy-soft and soaked in rich saffron milk. Their Chole Bhature makes for an amazing weekend lunch. Clean shop and friendly staff!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200'
  }
];
